name: Release
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: windows-latest
    steps:

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Extract Numeric Version
        shell: bash
        run: echo "VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/-.*//')" >> $GITHUB_ENV

      - name: Build
        shell: bash
        run: |
          dotnet build "./Source/" --configuration Release \
            -p:Version=${{ github.event.release.tag_name }} \
            -p:AssemblyVersion=${{ env.VERSION }}.0 \
            -p:FileVersion=${{ env.VERSION }}.0

      - name: Test
        run: dotnet test "./Source/" --configuration Release --no-build

      - name: Pack
        shell: bash
        run: |
          dotnet pack "./Source/Lib/Fluxor/Fluxor.csproj" --configuration Release --no-build \
            -p:Version=${{ github.event.release.tag_name }} \
            -p:AssemblyVersion=${{ env.VERSION }}.0 \
            -p:FileVersion=${{ env.VERSION }}.0 \
            -o artifacts

          dotnet pack "./Source/Lib/Fluxor.Blazor.Web/Fluxor.Blazor.Web.csproj" --configuration Release --no-build \
            -p:Version=${{ github.event.release.tag_name }} \
            -p:AssemblyVersion=${{ env.VERSION }}.0 \
            -p:FileVersion=${{ env.VERSION }}.0 \
            -o artifacts

          dotnet pack "./Source/Lib/Fluxor.Blazor.Web.ReduxDevTools/Fluxor.Blazor.Web.ReduxDevTools.csproj" --configuration Release --no-build \
            -p:Version=${{ github.event.release.tag_name }} \
            -p:AssemblyVersion=${{ env.VERSION }}.0 \
            -p:FileVersion=${{ env.VERSION }}.0 \
            -o artifacts

      - name: Push to NuGet
        run: |
          dotnet nuget push artifacts/Fluxor.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
          dotnet nuget push artifacts/Fluxor.Blazor.Web.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
          dotnet nuget push artifacts/Fluxor.Blazor.Web.ReduxDevTools.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
